import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./ui/Header/Header";
import Navigation from "./ui/Navigation/Navigation";

import { type Lang } from "./types/language";

import { LanguageProvider } from "./contexts/LanguageContext";
import { ThemeProvider } from "./contexts/ThemeContext";

import { cookies } from "next/headers";
import { Theme } from "@/types/theme";
import { NavbarProvider } from "./contexts/NavbarContext";

const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = ((await cookies()).get("lang")?.value || "ru") as Lang;
  const theme = ((await cookies()).get("theme")?.value || "light") as Theme;

  const navbarCookieState = (await cookies()).get("navbarIsOpen")?.value;
  const navbarState =
    navbarCookieState === undefined ? true : navbarCookieState === "true";

  return (
    <html className={`${theme}`} lang={lang}>
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider initialTheme={theme}>
          <LanguageProvider initialLang={lang}>
            <NavbarProvider initialState={navbarState}>
              <div className={`flex h-screen flex-col`}>
                <Header />
                <div className="flex flex-1 bg-bg">
                  <Navigation lang={lang} />
                  {children}
                </div>
              </div>
            </NavbarProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
